index:
    path: /
    methods: GET|HEAD
    controller: App\Controller\IndexController::index
#    condition:  "context.getMethod() in ['GET', 'HEAD'] and request.headers.get('User-Agent') matches '/firefox/i'"
#    condition: "request.headers.get('User-Agent') matches '%app.allowed_browsers%'"
#    expressions can also include config parameters:
